{"name": "test_get_user_profile", "status": "broken", "statusDetails": {"message": "TypeError: AuthAPI.get_profile() got an unexpected keyword argument 'headers'", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x000001EB60E5C830>\n\n    @pytest.mark.api\n    def test_get_user_profile(api_context):\n        user_profile = AuthAPI(api_context)\n>       user_profile_response = user_profile.get_profile(\n            headers = {\n                \"Authorization\": f\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3NTg2MTY0MTQsImV4cCI6MTc1ODYxODIxNH0.nv1oILdYSIPfEs9q205QjiKH9yqi8elFVEcD6fb2xeY\"\n            }\n        )\nE       TypeError: AuthAPI.get_profile() got an unexpected keyword argument 'headers'\n\ntest_login.py:46: TypeError"}, "start": 1758625962171, "stop": 1758625962171, "uuid": "de80aec4-68a7-4a8d-a405-87d092d19036", "historyId": "cb3dfa0bdd0cd85e7e5b9489b0b964af", "testCaseId": "cb3dfa0bdd0cd85e7e5b9489b0b964af", "fullName": "tests.test_login#test_get_user_profile", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "3336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}