{"name": "test_get_user_profile", "status": "broken", "statusDetails": {"message": "TypeError: AuthAPI.get_profile() got an unexpected keyword argument 'header'", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x0000021564D7C830>\n\n    @pytest.mark.api\n    def test_get_user_profile(api_context):\n        user_profile = AuthAPI(api_context)\n>       user_profile_response = user_profile.get_profile(\n            header=\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3NTg2MTY0MTQsImV4cCI6MTc1ODYxODIxNH0.nv1oILdYSIPfEs9q205QjiKH9yqi8elFVEcD6fb2xeY\" #token from login test\n        )\nE       TypeError: AuthAPI.get_profile() got an unexpected keyword argument 'header'\n\ntest_users_api.py:21: TypeError"}, "start": 1758625220999, "stop": 1758625220999, "uuid": "55ebe358-c205-47ee-ae51-6bdee37070fc", "historyId": "0e72d5562c233e937f091d40bf912d47", "testCaseId": "0e72d5562c233e937f091d40bf912d47", "fullName": "tests.test_users_api#test_get_user_profile", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_api"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "16112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_api"}], "titlePath": ["tests", "test_users_api.py"]}