{"name": "test_get_user_profile", "status": "broken", "statusDetails": {"message": "TypeError: AuthAPI.get_profile() got an unexpected keyword argument 'header'", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x0000023327AB0830>\n\n    @pytest.mark.api\n    def test_get_user_profile(api_context):\n        user_profile = AuthAPI(api_context)\n>       user_profile_response = user_profile.get_profile(\n            header=\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtaWx5cyIsImlkIjoxMCwiZXhwIjoxNzAxMDE2MDAwfQ.d8Hjv0Yk3bX4YtJHjvU4n8nX1Zz3y5g7y5y5y5y5y5y\" #token from login test\n        )\nE       TypeError: AuthAPI.get_profile() got an unexpected keyword argument 'header'\n\ntest_users_api.py:21: TypeError"}, "start": 1758625095372, "stop": 1758625095372, "uuid": "922c4328-0205-4d3b-8946-9a5a511f0023", "historyId": "0e72d5562c233e937f091d40bf912d47", "testCaseId": "0e72d5562c233e937f091d40bf912d47", "fullName": "tests.test_users_api#test_get_user_profile", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_api"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "19744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_api"}], "titlePath": ["tests", "test_users_api.py"]}