{"name": "test_login_valid_credentials", "status": "broken", "statusDetails": {"message": "TypeError: APIClient.post() got an unexpected keyword argument 'data'", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x000001F299204830>\n\n    @pytest.mark.api\n    def test_login_valid_credentials(api_context):\n        login_api = LoginAPI(api_context)\n>       response = login_api.login(\n            username=\"emilys\",\n            password=\"emilyspass\",\n            expiresInMins=30\n        )\n\ntest_login.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api.users_api.LoginAPI object at 0x000001F299204D70>, username = 'emilys', password = 'emilyspass', expiresInMins = 30\n\n    def login(self, username: str, password: str, expiresInMins: int = 60):\n        payload = {\n            \"username\": username,\n            \"password\": password,\n            \"expiresInMins\": expiresInMins\n        }\n>       return self.post(self.base_endpoint, data=payload)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       TypeError: APIClient.post() got an unexpected keyword argument 'data'\n\n..\\api\\users_api.py:22: TypeError"}, "start": 1758626834012, "stop": 1758626834012, "uuid": "88e732bd-cc31-4642-9937-2f382e91da7c", "historyId": "6401541eb30d027215dbf64771ce9e75", "testCaseId": "6401541eb30d027215dbf64771ce9e75", "fullName": "tests.test_login#test_login_valid_credentials", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "20836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}